= Do It!
:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: left
:toclevels: 4
:sectlinks:
:operation-curl-request-title: Example request
:operation-http-response-title: Example response

[[Member]]
== 회원

[[create-member]]
=== 회원가입
`POST`요청을 이용해 회원가입을 할 수 있다.

operation::create-member[snippets='request-fields,curl-request,http-request,request-headers,http-response,response-headers']

---

[[find-member]]
=== 회원조회
`GET`요청을 이용해 가입한 회원을 조회할 수 있다

operation::find-member[snippets='curl-request,http-request,http-response']

---

[[Team]]
== 팀

[[create-team]]
=== 팀만들기
`POST`요청으로 팀을 만들 수 있다

operation::create-team[snippets='request-fields,curl-request,http-request,request-headers,http-response']

---
[[Board]]
== 보드

[[create-board]]
=== 보드만들기
`POST`요청으로 팀을 만들 수 있다

operation::create-board[snippets='request-fields,curl-request,http-request,request-headers,http-response']

---

[[invite-member]]
=== 보드에 멤버초대하기
`PUT`요청으로 보드에 멤버를 초대할 수 있다.

operation::invite-member[snippets='curl-request,http-request,path-parameters,request-headers,http-response']

---

[[retrieve-my-board]]
=== 나의 보드 보기
`GET`요청으로 나의 보드를 볼 수 있다.

operation::retrieve-my-board[snippets='curl-request,http-request,request-headers,http-response,response-fields']

---

[[CardList]]
== 카드리스트

[[create-card-list]]
=== 카드리스트 만들기
`POST` 요청으로 카드리스트를 만들 수 있다.

operation::create-card-list[snippets='request-fields,curl-request,http-request,request-headers,http-response']
