spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/doit
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      format_sql: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
